# Generated by Django 3.1.1 on 2020-10-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetemp',
            name='image',
            field=models.ImageField(default='recipes_pics/default_recipe_image.jpg', upload_to='recipes_pics/'),
        ),
    ]
