# Generated by Django 3.1.1 on 2020-10-31 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0003_auto_20201031_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='recipes_pics/default_recipe_image.jpg', upload_to='recipes_pics/')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipes')),
            ],
            options={
                'db_table': 'recipes_images',
            },
        ),
        migrations.CreateModel(
            name='RecipesInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=500)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipes')),
            ],
            options={
                'db_table': 'recipes_information',
            },
        ),
        migrations.CreateModel(
            name='RecipesIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesIngredientsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipes')),
                ('recipe_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipesingredients')),
            ],
            options={
                'db_table': 'recipes_ingredients_items',
            },
        ),
        migrations.CreateModel(
            name='RecipesInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=500)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipes')),
            ],
            options={
                'db_table': 'recipes_instructions',
            },
        ),
        migrations.CreateModel(
            name='RecipesTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesTypesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipes')),
                ('recipe_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipestypes')),
            ],
            options={
                'db_table': 'recipes_types_items',
            },
        ),
        migrations.CreateModel(
            name='RecipesVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=1000)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.recipes')),
            ],
            options={
                'db_table': 'recipes_videos',
            },
        ),
        migrations.DeleteModel(
            name='RecipeTemp',
        ),
    ]
