# Generated by Django 3.1.1 on 2020-10-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20201031_2056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipesingredients',
            table='recipes_ingredients',
        ),
        migrations.AlterModelTable(
            name='recipestypes',
            table='recipes_types',
        ),
    ]
