# Generated by Django 3.1.1 on 2020-10-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20201031_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesingredientsitems',
            old_name='recipe_type_id',
            new_name='recipe_ingredient_id',
        ),
    ]
